version: '3.2'
services:
    db:
        image: mysql
        container_name: db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: colombia.1029
            MYSQL_DATABASE: schoolvote
        ports:
        - "3310:3310"
    app:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
